-- gitsigns.lua — Git gutter signs (replaces vim-gitgutter)

return {
  "lewis6991/gitsigns.nvim",
  event = { "BufReadPre", "BufNewFile" },
  opts = {
    signs = {
      add = { text = " " },
      change = { text = " " },
      delete = { text = " " },
      topdelete = { text = " " },
      changedelete = { text = " " },
      untracked = { text = " " },
    },
    signcolumn = true,
    numhl = false,
    linehl = false,
    word_diff = false,
    watch_gitdir = { interval = 1000, follow_files = true },
    attach_to_untracked = true,
    current_line_blame = false,
    current_line_blame_opts = { delay = 1000 },
    sign_priority = 6,
    update_debounce = 100,
    max_file_length = 40000,
  },
  keys = {
    { "<Leader>hs", "<Cmd>Gitsigns stage_hunk<CR>",       desc = "Stage hunk" },
    { "<Leader>hr", "<Cmd>Gitsigns reset_hunk<CR>",       desc = "Reset hunk" },
    { "<Leader>hS", "<Cmd>Gitsigns stage_buffer<CR>",     desc = "Stage buffer" },
    { "<Leader>hu", "<Cmd>Gitsigns undo_stage_hunk<CR>",  desc = "Undo stage hunk" },
    { "<Leader>hp", "<Cmd>Gitsigns preview_hunk<CR>",     desc = "Preview hunk" },
    { "<Leader>hb", "<Cmd>Gitsigns blame_line<CR>",       desc = "Blame line" },
    { "<Leader>hd", "<Cmd>Gitsigns diffthis<CR>",         desc = "Diff this" },
    { "<Leader>hD", "<Cmd>Gitsigns diffthis ~<CR>",       desc = "Diff this ~" },
    { "<Leader>htb", "<Cmd>Gitsigns toggle_current_line_blame<CR>", desc = "Toggle line blame" },
    { "]h", "<Cmd>Gitsigns next_hunk<CR>",                 desc = "Next hunk" },
    { "[h", "<Cmd>Gitsigns prev_hunk<CR>",                 desc = "Previous hunk" },
  },
}
